version: '3'
services:
  mapgen-frontend:
    build:
      context: .
      dockerfile: ./container/frontend/Dockerfile
    image: ghcr.io/xcsoar/mapgen-frontend
    ports:
      - "9091:9090"
    volumes:
      - mapgen-jobs:/opt/mapgen/jobs
  mapgen-worker:
    build:
      context: .
      dockerfile: ./container/worker/Dockerfile
    image: ghcr.io/xcsoar/mapgen-worker
    environment:
      - MAPGEN_DATA_URL=${MAPGEN_DATA_URL:-https://mapgen-data.sigkill.ch/}
      - MAPGEN_DEM_DATASET=${MAPGEN_DEM_DATASET:-}
      - MAPGEN_DEM_EXTENSIONS=${MAPGEN_DEM_EXTENSIONS:-}
      - MAPGEN_HIGH_QUALITY_DATA_URL=${MAPGEN_HIGH_QUALITY_DATA_URL:-file:///opt/mapgen/high-quality-data/}
      - MAPGEN_HIGH_QUALITY_DEM_DATASET=${MAPGEN_HIGH_QUALITY_DEM_DATASET:-dem1}
      - MAPGEN_HIGH_QUALITY_DEM_EXTENSIONS=${MAPGEN_HIGH_QUALITY_DEM_EXTENSIONS:-tif}
      - MAPGEN_ESTIMATED_POWER_WATTS=${MAPGEN_ESTIMATED_POWER_WATTS:-25}
    volumes:
      - mapgen-jobs:/opt/mapgen/jobs
      - mapgen-data:/opt/mapgen/data
      - ${MAPGEN_HIGH_QUALITY_DATA_DIR:-/home/slawek/mapgen-data-nowa_mapa2/repo}:/opt/mapgen/high-quality-data:ro

volumes:
  mapgen-data:
  mapgen-jobs:
